version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: "server"
    ports:
      - "4090:3000"
    volumes:
      - ./server:/app
    command: air run src/cmd/main.go -b 0.0.0.0

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: "client"
    ports:
      - "80:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
